[book]
authors = ["Phodal Huang"]
language = "zh-cn"
multilingual = false
src = "book-src"
title = "HarmonyOS with AIGC"

[output.html]
git-repository-url = "https://github.com/harmonyos-dev/aigc-harmonyos-sample"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/harmonyos-dev/aigc-harmonyos-sample/edit/master/{path}"
site-url = "/"
additional-js = ["assets/custom.js"]
